### ISSUE TITLE
Change CompoundTag::get_vec() visibility to public

### ISSUE THREAD

**Issue by oOBoomberOo** [eihwaz/named-binary-tag#11]
Right now it can't be used by other library because it is private and I don't see the reason why it need to be that way.

**Comment by vaIgarashi** [comment]
It's private because i don't want to expose publicly Tag structure. Why this may be needed? There are methods to extract value from tag

**Comment by oOBoomberOo** [comment]
The current implementation of `CompoundTag` lacks a way to get the vector form of `float (f32)`, `double (f64)`, and `short (i16)` which is all a valid type in NBT format.
If you don't want to expose the Tag structure then I think you should implement these methods too.

**Comment by vaIgarashi** [comment]
I agree with you
