### ISSUE TITLE
Zero copy abstraction

### ISSUE THREAD

**Issue by vaIgarashi** [eihwaz/named-binary-tag#7]
Currently we require ownership of `CompoundTag` to serialize it. This ends with cloning. We may do this better.

**Comment by vagola** [comment]
I have been working to switch on `Cow` smart pointer. I had to add `'a` lifetime to `Tag` and this lead to errors like:

`
error[E0515]: cannot return value referencing local variable `reader`
  --> src/decode.rs:37:5
   |
37 |     read_compound_tag(&mut reader)
   |     ^^^^^^^^^^^^^^^^^^-----------^
   |     |                 |
   |     |                 `reader` is borrowed here
   |     returns a value referencing data owned by the current function
```

**Comment by SpecificProtagonist** [comment]
I've submitted PR #16 to fix this.

That said, there also are avoidable copies being made when getting or setting lists as well as when inserting strings.

**Comment by vaIgarashi** [comment]
Great job. Thanks for the contribution
