### ISSUE TITLE
Docs.rs not rendering documentation

### ISSUE THREAD

**Issue by kotauskas** [eihwaz/named-binary-tag#9]
The [`docs.rs` page][docsrs] states that "`named-binary-tag-0.2.3` doesn't have any documentation", which is obviously false, as seen by merely peeking into the code. What could possibly be the cause of that?

[docsrs]: https://docs.rs/crate/named-binary-tag "named-binary-tag on Docs.rs"

**Comment by vaIgarashi** [comment]
I have contacted the docs.rs team. There were a bug due the lib rename in Cargo.toml. It was fixed few months ago. They were nice and rebuilded the docs. Now it's correctly rendered.
